version: '3'
services:

  app:
    build: .
    environment:
      - DB_URL=mongodb://mongo:27017/canine-dev
    env_file:
      - .env.development.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      
  mongo:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge
